build:
    environment:
        php: '5.4.28
checks:
    php:
        code_rating: true
        duplication: true
tools:
    php_code_sniffer: true
    php_cs_fixer: true
    php_mess_detector: true
    sensiolabs_security_checker: true
    php_sim:
        enabled: true
        min_mass: 16
        filter:
            excluded_paths:
                - 'tests/*'
            paths: {  }
    php_pdepend:
        enabled: true
        configuration_file: null
        suffixes:
            - php
        excluded_dirs: {  }
        filter:
            excluded_paths:
                - 'tests/*'
            paths: {  }
    php_analyzer:
        enabled: true
        extensions:
            - php
        dependency_paths: {  }
        filter:
            excluded_paths:
                - 'tests/*'
            paths: {  }
        path_configs: {  }
    php_changetracking:
        enabled: true
        bug_patterns:
            - '\bfix(?:es|ed)?\b'
        feature_patterns:
            - '\badd(?:s|ed)?\b'
            - '\bimplement(?:s|ed)?\b'
        filter:
            excluded_paths:
                - 'tests/*'
            paths: {  }
filter:
    excluded_paths:
        - 'tests/*'
    paths: [src/*]
build_failure_conditions: {  }
